import type { Gift } from "./types"

export const mockGifts: Gift[] = [
  {
    id: "1",
    name: "Cozy Knit Throw Blanket",
    brand: "Comfort Home",
    price: 45.99,
    rating: 4.8,
    reviewCount: 1247,
    image: "/placeholder-rkc74.png",
    shopUrl: "https://example.com/blanket",
    category: "Home & Living",
  },
  {
    id: "2",
    name: "Premium Tea Sampler Set",
    brand: "Tea Masters",
    price: 32.5,
    rating: 4.9,
    reviewCount: 892,
    image: "/premium-tea-sampler.png",
    shopUrl: "https://example.com/tea-set",
    category: "Food & Beverage",
  },
  {
    id: "3",
    name: "Aromatherapy Essential Oil Diffuser",
    brand: "Zen Living",
    price: 67.99,
    rating: 4.7,
    reviewCount: 2156,
    image: "/aromatherapy-diffuser.png",
    shopUrl: "https://example.com/diffuser",
    category: "Wellness",
  },
  {
    id: "4",
    name: "Personalized Photo Album",
    brand: "Memory Lane",
    price: 28.99,
    rating: 4.6,
    reviewCount: 634,
    image: "/placeholder-wv5h2.png",
    shopUrl: "https://example.com/photo-album",
    category: "Personalized",
  },
  {
    id: "5",
    name: "Gourmet Chocolate Collection",
    brand: "Sweet Delights",
    price: 39.99,
    rating: 4.8,
    reviewCount: 1543,
    image: "/gourmet-chocolate-gift-box.png",
    shopUrl: "https://example.com/chocolate",
    category: "Food & Beverage",
  },
  {
    id: "6",
    name: "Silk Scarf with Floral Pattern",
    brand: "Elegant Accessories",
    price: 55.0,
    rating: 4.5,
    reviewCount: 789,
    image: "/elegant-floral-silk-scarf.png",
    shopUrl: "https://example.com/scarf",
    category: "Fashion",
  },
]
