import type { Gift } from "./types"

export const mockGifts: Gift[] = [
  {
    id: "1",
    name: "Cozy Knit Throw Blanket",
    brand: "Comfort Home",
    price: 45.99,
    rating: 4.8,
    reviewCount: 1247,
    image: "/placeholder-rkc74.png",
    shopUrl: "https://www.target.com/p/cozy-knit-throw-blanket/-/A-54321098",
    category: "Home & Living",
    tags: ["mom", "cozy", "home"],
  },
  {
    id: "2",
    name: "Premium Tea Sampler Set",
    brand: "Tea Masters",
    price: 32.5,
    rating: 4.9,
    reviewCount: 892,
    image: "/premium-tea-sampler.png",
    shopUrl: "https://www.williams-sonoma.com/products/premium-tea-sampler-set/",
    category: "Food & Beverage",
    tags: ["birthday", "wellness", "tea lover"],
  },
  {
    id: "3",
    name: "Aromatherapy Essential Oil Diffuser",
    brand: "Zen Living",
    price: 67.99,
    rating: 4.7,
    reviewCount: 2156,
    image: "/aromatherapy-diffuser.png",
    shopUrl: "https://www.amazon.com/dp/diffuser",
    category: "Wellness",
    tags: ["wellness", "relaxation", "mom"],
  },
  {
    id: "4",
    name: "Personalized Photo Album",
    brand: "Memory Lane",
    price: 28.99,
    rating: 4.6,
    reviewCount: 634,
    image: "/placeholder-wv5h2.png",
    shopUrl: "https://www.amazon.com/dp/photo-album",
    category: "Personalized",
    tags: ["anniversary", "memories", "personalized"],
  },
  {
    id: "5",
    name: "Gourmet Chocolate Collection",
    brand: "Sweet Delights",
    price: 39.99,
    rating: 4.8,
    reviewCount: 1543,
    image: "/gourmet-chocolate-gift-box.png",
    shopUrl: "https://www.amazon.com/dp/chocolate",
    category: "Food & Beverage",
    tags: ["birthday", "valentine", "sweet tooth"],
  },
  {
    id: "6",
    name: "Silk Scarf with Floral Pattern",
    brand: "Elegant Accessories",
    price: 55.0,
    rating: 4.5,
    reviewCount: 789,
    image: "/elegant-floral-silk-scarf.png",
    shopUrl: "https://www.amazon.com/dp/scarf",
    category: "Fashion",
    tags: ["mom", "elegant", "fashion"],
  },
  {
    id: "7",
    name: "Wireless Noise-Canceling Headphones",
    brand: "SoundTech Pro",
    price: 199.99,
    rating: 4.7,
    reviewCount: 3421,
    image: "/wireless-headphones.png",
    shopUrl: "https://www.amazon.com/dp/headphones",
    category: "Electronics",
    tags: ["tech", "music lover", "teenager"],
  },
  {
    id: "8",
    name: "Smart Fitness Watch",
    brand: "FitTrack",
    price: 249.99,
    rating: 4.6,
    reviewCount: 2890,
    image: "/smart-fitness-watch.png",
    shopUrl: "https://www.amazon.com/dp/fitness-watch",
    category: "Electronics",
    tags: ["fitness", "health", "tech"],
  },
  {
    id: "9",
    name: "Coffee Subscription Box",
    brand: "Bean There",
    price: 29.99,
    rating: 4.8,
    reviewCount: 1876,
    image: "/coffee-subscription-box.png",
    shopUrl: "https://www.amazon.com/dp/coffee-box",
    category: "Food & Beverage",
    tags: ["coffee lover", "subscription", "monthly"],
  },
  {
    id: "10",
    name: "Luxury Candle Set",
    brand: "Ambiance Co",
    price: 42.99,
    rating: 4.9,
    reviewCount: 1234,
    image: "/luxury-candle-set.png",
    shopUrl: "https://www.amazon.com/dp/candles",
    category: "Home & Living",
    tags: ["relaxation", "home", "cozy"],
  },
  {
    id: "11",
    name: "Artisan Jewelry Box",
    brand: "Craft Masters",
    price: 78.99,
    rating: 4.7,
    reviewCount: 987,
    image: "/artisan-jewelry-box.png",
    shopUrl: "https://www.amazon.com/dp/jewelry-box",
    category: "Home & Living",
    tags: ["elegant", "storage", "handmade"],
  },
  {
    id: "12",
    name: "Gourmet Cooking Spice Set",
    brand: "Chef's Choice",
    price: 34.99,
    rating: 4.8,
    reviewCount: 2156,
    image: "/gourmet-spice-set.png",
    shopUrl: "https://www.amazon.com/dp/spices",
    category: "Food & Beverage",
    tags: ["cooking", "foodie", "gourmet"],
  },
  {
    id: "13",
    name: "Bamboo Cutting Board Set",
    brand: "EcoKitchen",
    price: 45.99,
    rating: 4.6,
    reviewCount: 1543,
    image: "/bamboo-cutting-board.png",
    shopUrl: "https://www.amazon.com/dp/cutting-board",
    category: "Kitchen",
    tags: ["eco-friendly", "cooking", "kitchen"],
  },
  {
    id: "14",
    name: "Meditation Cushion",
    brand: "Zen Studio",
    price: 56.99,
    rating: 4.5,
    reviewCount: 876,
    image: "/meditation-cushion.png",
    shopUrl: "https://www.amazon.com/dp/meditation",
    category: "Wellness",
    tags: ["meditation", "wellness", "mindfulness"],
  },
  {
    id: "15",
    name: "Vintage Wine Glasses Set",
    brand: "Crystal Clear",
    price: 89.99,
    rating: 4.7,
    reviewCount: 1987,
    image: "/vintage-wine-glasses.png",
    shopUrl: "https://www.amazon.com/dp/wine-glasses",
    category: "Home & Living",
    tags: ["elegant", "wine lover", "entertaining"],
  },
  {
    id: "16",
    name: "Portable Phone Charger",
    brand: "PowerUp",
    price: 24.99,
    rating: 4.4,
    reviewCount: 3456,
    image: "/portable-charger.png",
    shopUrl: "https://www.amazon.com/dp/charger",
    category: "Electronics",
    tags: ["tech", "practical", "travel"],
  },
  {
    id: "17",
    name: "Handwoven Basket Set",
    brand: "Artisan Crafts",
    price: 67.99,
    rating: 4.8,
    reviewCount: 1234,
    image: "/handwoven-baskets.png",
    shopUrl: "https://www.amazon.com/dp/baskets",
    category: "Home & Living",
    tags: ["handmade", "storage", "rustic"],
  },
  {
    id: "18",
    name: "Premium Skincare Set",
    brand: "Glow Beauty",
    price: 125.99,
    rating: 4.9,
    reviewCount: 2876,
    image: "/premium-skincare.png",
    shopUrl: "https://www.amazon.com/dp/skincare",
    category: "Beauty",
    tags: ["skincare", "luxury", "self-care"],
  },
  {
    id: "19",
    name: "Bluetooth Speaker",
    brand: "SoundWave",
    price: 79.99,
    rating: 4.6,
    reviewCount: 2134,
    image: "/bluetooth-speaker.png",
    shopUrl: "https://www.amazon.com/dp/speaker",
    category: "Electronics",
    tags: ["music", "tech", "portable"],
  },
  {
    id: "20",
    name: "Organic Herb Garden Kit",
    brand: "Green Thumb",
    price: 36.99,
    rating: 4.7,
    reviewCount: 1567,
    image: "/herb-garden-kit.png",
    shopUrl: "https://www.amazon.com/dp/garden-kit",
    category: "Garden",
    tags: ["gardening", "organic", "herbs"],
  },
  {
    id: "21",
    name: "Cashmere Throw Pillow",
    brand: "Luxury Living",
    price: 58.99,
    rating: 4.8,
    reviewCount: 987,
    image: "/cashmere-pillow.png",
    shopUrl: "https://www.amazon.com/dp/pillow",
    category: "Home & Living",
    tags: ["luxury", "comfort", "home decor"],
  },
  {
    id: "22",
    name: "Artisan Coffee Mug",
    brand: "Pottery Works",
    price: 22.99,
    rating: 4.5,
    reviewCount: 1876,
    image: "/artisan-coffee-mug.png",
    shopUrl: "https://www.amazon.com/dp/mug",
    category: "Kitchen",
    tags: ["handmade", "coffee", "ceramic"],
  },
  {
    id: "23",
    name: "Yoga Mat Premium",
    brand: "FlexFit",
    price: 68.99,
    rating: 4.7,
    reviewCount: 2345,
    image: "/premium-yoga-mat.png",
    shopUrl: "https://www.amazon.com/dp/yoga-mat",
    category: "Fitness",
    tags: ["yoga", "fitness", "wellness"],
  },
  {
    id: "24",
    name: "Gourmet Olive Oil Set",
    brand: "Mediterranean Gold",
    price: 49.99,
    rating: 4.9,
    reviewCount: 1654,
    image: "/gourmet-olive-oil.png",
    shopUrl: "https://www.amazon.com/dp/olive-oil",
    category: "Food & Beverage",
    tags: ["gourmet", "cooking", "Mediterranean"],
  },
  {
    id: "25",
    name: "Smart Home Diffuser",
    brand: "TechScent",
    price: 94.99,
    rating: 4.6,
    reviewCount: 1432,
    image: "/smart-diffuser.png",
    shopUrl: "https://www.amazon.com/dp/smart-diffuser",
    category: "Electronics",
    tags: ["smart home", "aromatherapy", "tech"],
  },
  {
    id: "26",
    name: "Handcrafted Leather Journal",
    brand: "Artisan Books",
    price: 41.99,
    rating: 4.8,
    reviewCount: 876,
    image: "/leather-journal.png",
    shopUrl: "https://www.amazon.com/dp/journal",
    category: "Stationery",
    tags: ["writing", "leather", "handmade"],
  },
  {
    id: "27",
    name: "Ceramic Plant Pot Set",
    brand: "Garden Style",
    price: 33.99,
    rating: 4.5,
    reviewCount: 1987,
    image: "/ceramic-plant-pots.png",
    shopUrl: "https://www.amazon.com/dp/plant-pots",
    category: "Garden",
    tags: ["plants", "ceramic", "home decor"],
  },
  {
    id: "28",
    name: "Premium Bath Towel Set",
    brand: "Luxury Bath",
    price: 76.99,
    rating: 4.7,
    reviewCount: 2134,
    image: "/premium-towels.png",
    shopUrl: "https://www.amazon.com/dp/towels",
    category: "Home & Living",
    tags: ["luxury", "bath", "comfort"],
  },
  {
    id: "29",
    name: "Wireless Charging Pad",
    brand: "ChargeTech",
    price: 35.99,
    rating: 4.4,
    reviewCount: 2876,
    image: "/wireless-charging-pad.png",
    shopUrl: "https://www.amazon.com/dp/charging-pad",
    category: "Electronics",
    tags: ["tech", "wireless", "convenience"],
  },
  {
    id: "30",
    name: "Artisan Soap Collection",
    brand: "Pure Essence",
    price: 28.99,
    rating: 4.8,
    reviewCount: 1543,
    image: "/artisan-soap-collection.png",
    shopUrl: "https://www.amazon.com/dp/soap-collection",
    category: "Beauty",
    tags: ["natural", "handmade", "skincare"],
  },
]
